### ISSUE TITLE
Product tiles

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#2]
images not showing per product on brand and shop pages

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
I'm still getting this 

![Screenshot 2023-07-14 15 04 06](https://github.com/markendley/frste/assets/90736622/9b30a24f-e478-44dc-a932-918248e0e1c9)

**Comment by markendley** [comment]
whoops try again

**Comment by Treadstudio** [comment]
yep that works, some of the products are cutting off a little bit, can we adjust?

**Comment by markendley** [comment]
I see the images that you're uploading.

I don't need to stretch the image to fill the container.

But can you make them so none of them are cropped from the sides? (cropped from the bottom would be ok).

Otherwise, we should make these cards sqaure, and do something like this....

<img width="1496" alt="Screenshot 2023-07-17 at 4 10 07 pm" src="https://github.com/markendley/frste/assets/6570606/8ee5618f-fec7-4cc7-b8d8-cf49a8d4c126">

**Comment by Treadstudio** [comment]
na all good. i'll just make sure they aren't cropped from the sides. Easily.
