### ISSUE TITLE
https://demoplatform.net/frste/shop/

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#57]
can we change "shop" to "products" at the top?

**Comment by markendley** [comment]
done

**Comment by Treadstudio** [comment]
i can see the URL update but it is still showing "shop on the page" and the update has caused a bug with the filters.

![Screenshot 2023-07-28 09 41 12](https://github.com/markendley/frste/assets/90736622/c56e7396-2199-4e7a-b85f-3af51042b19b)

**Comment by markendley** [comment]
oh that Top

done

fixed
